### ISSUE TITLE
Add a stack.yaml

### ISSUE THREAD

**Issue by lethom** [imalsogreg/servant-reflex#10]
I use stack rather than nix and I wrote a very small stack.yaml file which works for servant-reflex.

Do you want me to make a PR with these changes?

**Comment by imalsogreg** [comment]
I don't use stack personally and wouldn't be able to maintain a stack.yaml file. Would it help you (or others) to have the stack file in this repo? (n.b. I expect our deps will get a lot cleaner as some of our main dependencies get to hackage). Do Haskell libraries typically come with stack.yaml files, or is there one stack.yaml for a final project?

**Comment by mightybyte** [comment]
A stack.yaml file fixes users to one particular version of all of the dependencies.  This isn't very flexible for libraries as you usually want them to be buildable with a wider range of dependency versions.  I think stack.yaml is something that end users should create for themselves and not supplied by libraries.

**Comment by imalsogreg** [comment]
Sounds like I can close this. Thanks both.
