### ISSUE TITLE
Question: How does one map a Client function over a list of values in an Event?

### ISSUE THREAD

**Issue by rprije** [imalsogreg/servant-reflex#103]
I have some servant-reflex functions successfully performing queries. One query produces a list of identifiers. The interesting parts look something roughly like this:

```
Event t tag -> m (Event t (ReqResult tag [identifier]))
```

I then have another function which goes and retrieves the full item based upon the identfiier. Something like this:

```
Dynamic t (Either Text identifier) -> Event t tag -> m (Event t (ReqResult tag a))
```

ie it takes a single identifier. I'd like to map the second function over the list contained in the result of the first and have the triggering event be the resulting event of the first. However a simple mapping results in something like `Event t (m [Event t (ReqResult tag a)])`.

With a big mess of `holdDyn`, `join`, `dyn`, `widgetHold` etc I can get something that looks like `m (Event t [result])` but that second function never fires and the `Event` stays at the default of `[]` needed for the many `holdDyn`s and `widgetHold`s. I haven't been able to track down why but I gather it's because I'm not handling fanout or maybe a promptly function is needed somewhere.

I considered instead building up my own invocation of `performRequestsCT` that takes instead the list I want to map over but I'm unable to build the `Req` I need using the functions externally visible in the library and anyway that loses servant-reflex's nice API safety features..

Anyway, is such a mapping common practice and if so, how does one sensibly go about it?

One of my horrible, failed attempts as an example:

```
getIds'
  :: (MonadFix m, MonadHold t m, NotReady t m, Adjustable t m, PostBuild t m)
  => (Dynamic t (Either Text id) -> Event t () -> m (Event t result))
  -> Event t [id]
  -> m (Dynamic t [result])
getIds' f idsEv = do
  dynEvs <- mapEvList' f' idsEv
  evDynRes <- dyn $ gatherEvList <$> dynEvs
  join <$> holdDyn (constDyn []) evDynRes
  where
    f' id' = f (constDyn $ Right id') (idsEv $> ())

mapEvList'
  :: (MonadHold t m, Adjustable t m)
  => (a -> m b)
  -> Event t [a]
  -> m (Dynamic t [b])
mapEvList' f ev =  widgetHold (pure []) $ mapM f <$> ev

gatherEvList
  :: (Reflex t, MonadFix m, MonadHold t m)
  => [Event t a]
  -> m (Dynamic t [a])
gatherEvList = foldM f $ constDyn []
  where
    f d ev = join <$> foldDyn f' d ev
    f' a d = (a:) <$> d
```

**Comment by imalsogreg** [comment]
Hello, great question! It can be hard to do monadic things with servant-reflex requests/responses. I think your `widgetHold`s may be clobbering each other?

When sending multiple requests in a single point in time, some special handling is needed in order to keep track of which response belongs to which request, and that's what the [clientA](https://hackage.haskell.org/package/servant-reflex-0.3.5/docs/Servant-Reflex-Multi.html#v:clientA) version of the API is for. I gave just a brief description of clientA in the readme [here](https://github.com/imalsogreg/servant-reflex/#simultaneous-requests). Could you see if that fits your problem? I would expect you just need a `tagPromptlyDyn` on your `[Identifier]` response to generate both the `Identifier -> a` requests and the trigger events. In other words, treat the responses to your first endpoint as the triggers that initiate the `clientA` bulk request. Let me know if that is unclear :)

**Comment by rprije** [comment]
Thanks! I hadn't really noticed the `Servant.Reflex.Multi`. That seems very appropriate!

My API uses `Capture` and the `HasClientMulti` instance for this wraps the function argument up as a `f (Dynamic t (Either Text a))` (https://github.com/imalsogreg/servant-reflex/blob/dac560cdb65ffaaa78d5ab800b8aa52ed011f44a/src/Servant/Reflex/Multi.hs#L123-L124)

However I notice that the README and code shows things like `QParam` arguments producing `Dynamic t (f (QParam a))` arguments with the `f` inside the `Dynamic` instead of the other way around. This aligns better with my use case and I think is what you were assuming in your reply. Why is the orientation of the `Capture` arguments different?

**Comment by rprije** [comment]
I was able to get my thing working by introducing a delay on the triggering `Event`. I think things got a little confused having my computations get created inside the same `Event` that was being used to construct argument to the computations. Without the delay and using the event directly, the computation would just never fire at all.

(and, as an aside, thanks for building this library. Having my Reflex client functions automatically constructed from my Servant API is very neat)

```
getAllById
  :: forall m t f id result
   . ( MonadFix m, MonadHold t m, Adjustable t m
     , PerformEvent t m, TriggerEvent t m, MonadIO (Performable m)
     , Monoid (f result), Traversable f, Applicative f)
  => (   f (Dynamic t (Either Text Authority))
      -> f (Dynamic t (Either Text id))
      -> Event t ()
      -> m (Event t (f result)))
  -> Dynamic t (Either Text Authority)
  -> Event t (f id)
  -> m (Event t (m (Dynamic t (f result))))
getAllById getCmd authDyn idsEv = do
  triggerEv <- delay 0.1 idsEv
  pure $ getIds (triggerEv $> ()) <$> idsEv
  where
    getIds triggerEv ids = do
      let idDyns = fmap (constDyn . Right) ids
      resultsEv <- getCmd (pure authDyn) idDyns (triggerEv $> ())
      foldDyn (<>) mempty resultsEv
```
