### ISSUE TITLE
"bad request": my request gets formed without payload

### ISSUE THREAD

**Issue by rubenmoor** [imalsogreg/servant-reflex#120]
see also here: https://discourse.haskell.org/t/servant-and-servant-reflex-debugging-a-bad-request/4715

I added a route to my api, like this:

```
type RoutesAdmin =
  AuthRequired "jwt" :> "journal" :> ReqBody '[JSON] (UTCTime, UTCTime) :> Get '[JSON] [Journal]
```

I use `servant-reflex` for client-side code like this:

```
getJournalAll
    :: SupportsServantReflex t m
    => Dynamic t (Either Text (CompactJWT, Text))
    -> Dynamic t (Either Text (UTCTime, UTCTime))
    -> Event t ()
    -> m (Event t (ReqResult () [Journal]))

((postConfigNew :<|> getDocDEPatternAll :<|> getDocDEPattern :<|> getDictDE :<|> getDictDENumbers) :<|> (getJournalAll) :<|> (postAuthenticate :<|> postAuthNew :<|> postDoesUserExist :<|> postLogout) :<|> ((postAliasRename :<|> getAliasAll :<|> postAliasSetDefault) :<|> (getAppState :<|> postAppState)) :<|> (postEventViewPage :<|> postEventStageCompleted))
    = client (Proxy :: Proxy RoutesApi)
             (Proxy :: Proxy (m :: * -> *))
             (Proxy :: Proxy ())
             (constDyn (BasePath "/"))
```

And I call `getJournalAll` like this:

```
    evResp <- fmap switchDyn $ prerender (pure never) $
        getJournalAll (getAuthData <$> dynState) dynStartEnd evReady
```

I checked that `dynStartEnd` has indeed a `Right`-value inside (the error for a `Left` would be a different one, anyway). But in the browser I can see that the server responds with a "400 bad request". Checking the request, I realize it was sent without a payload, so indeed malformed. But I don't know why.

My api contains a lot of requests, with and without `AuthRequired ` (my custom authentication combinator), with and without `ReqBody`. This is the only one that somehow behaves weird.

Any idea where to look for the error?

**Comment by rubenmoor** [comment]
I was able to reproduce the problem with a hand-written XHR. Even though the server responds with a 400/Bad Request, the cause of the problem is not `servant-reflex`.

**Comment by imalsogreg** [comment]
@rubenmoor Thanks for the report! Are you using `servant-snap` as the server?

**Comment by rubenmoor** [comment]
> @rubenmoor Thanks for the report! Are you using `servant-snap` as the server?

Yes, indeed servant-snap

**Comment by rubenmoor** [comment]
cf. https://github.com/haskell-servant/servant-snap/issues/33
