### ISSUE TITLE
Add a real license file.

### ISSUE THREAD

**Issue by ojw** [imalsogreg/servant-reflex#18]
This project is great and I want to use it!  However, it has an empty license file, so I don't think that I can.  If you intend this to be an open source project and have a preferred license, I can throw together a pull request updating the license file.

**Comment by imalsogreg** [comment]
Good catch. I'd very gladly take a PR with a real license file. BSD3 ok? Thanks!

**Comment by imalsogreg** [comment]
Closed by #19
