### ISSUE TITLE
Event does not fire at the end of request?

### ISSUE THREAD

**Issue by NorfairKing** [imalsogreg/servant-reflex#39]
I may be understanding this massively, so feel free to tell me if this is the wrong repository to open an issue at.

I'm trying to make some sort of list of text items that can be added to, and the addition can be synced to a server (that part works).
Then I want to show a list of items that each have a delete button.
When the delete button is clicked, that deletion needs to be synced as well.
This is where things go wrong.
The button click seems to fire correctly, and the deletion syncing requests fires correctly as well, but the event that should signal the event of the request finishing does not fire (traceEvent does not print anything).

This is the relevant code:

```
data LocalItemAddedState
    = Unsynced
    | AddingSyncError Error
    | Synced InboxItemUUID
    deriving (Show, Eq, Generic)

data ItemDeletedEvent
    = ItemDeletedEvent
    | ItemDeletionSynced
    | ErrorWhileDeletingItem Text
    deriving (Show, Eq, Generic)

makeDeletionButton ::
       forall t m. MonadWidget t m
    => Dynamic t BaseUrl
    -> LocalItemAddedState
    -> m (Event t (NonEmpty ItemDeletedEvent))
makeDeletionButton dynBurl lias = do
    buttonEvent <- button "Delete"
    let e1 = tagPromptlyDyn (constDyn ItemDeletedEvent) buttonEvent
    e2 <-
        case lias of
            Synced uuid -> do
                let eitherDynt = Right <$> constDyn uuid
                deletedRequestEvent <-
                    clientDeleteItem dynBurl eitherDynt buttonEvent :: m (Event t (ReqResult () ()))
                let deletedEventEvent =
                        flip fmap deletedRequestEvent $ \rr ->
                            case rr of
                                ResponseSuccess () () _ -> ItemDeletionSynced
                                ResponseFailure () err _ ->
                                    ErrorWhileDeletingItem err
                                RequestFailure () err ->
                                    ErrorWhileDeletingItem err
                pure $ Just deletedEventEvent
            _ -> pure Nothing
    pure $ mergeList $ catMaybes [Just e1, e2]
```

Any help would be appreciated!

**Comment by imalsogreg** [comment]
Interesting problem. Definitely feel free to post issues like this here.

My first thought is that maybe code outside of the snippet you posted is doing something with the `ItemDeletedEvent`s that come directly from the button clicks (`Just e1`), such as deleting the row?

The direction I would go, both to solve this issue and to make other patterns easier, would be to make the list items less self-controlling. I would delegate both (a) management of the DOM elements of the list and (b) management of communication with the server to some stateful code that lives just outside of the `<ul>`.

**Comment by NorfairKing** [comment]
@imalsogreg Thanks for the help! I'll try that. After a bunch of discussion on #reflex-frp, I'm convinced this is certainly not `servant-reflex`'s fault. Closing this.
