### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NCrashed** [imalsogreg/servant-reflex#42]
Hi,

In cabal file license is set to unfree `AllRightsReserved`, but `LICENSE.md` corresponds to BSD3. So, `cabal2nix` treats the package as proprietary. It makes some burdensome while using via nixos. 

Is there any paticular reason to not have BSD3 in cabal file explicitly?

**Comment by imalsogreg** [comment]
Thank you for opening a ticket - I hadn't noticed this! Fixed in b35b7da1db4e28eacf7e9f2de1a0cee6726180d6
