### ISSUE TITLE
Provide access to original XHR request for debugging purposes

### ISSUE THREAD

**Issue by 3noch** [imalsogreg/servant-reflex#45]
As far as I know there is no way to look at the raw XHR request being sent. This would be very helpful in debugging.

I can't think of a good design for this though. The only idea I have is to add it to the `ReqResponse`.

**Comment by NorfairKing** [comment]
Maybe just have a `debug-requests` flag with CPP?

**Comment by 3noch** [comment]
@NorfairKing That would work, although it's heavy-handed IMO.

Actually I can see the value in providing a derived client that doesn't actually make a request at all, but just hands you the XHR request object and lets you do what you want.

**Comment by imalsogreg** [comment]
Closed by #47
