### ISSUE TITLE
Permit zero content types for empty response

### ISSUE THREAD

**Issue by jekor** [imalsogreg/servant-reflex#51]
See https://github.com/haskell-servant/servant/issues/69

Error:

```
    • Couldn't match type ‘'[]’ with ‘ct0 : cts0’
        arising from a use of ‘client’
```

Relevant code:

```
Delete '[] ()
```

**Comment by imalsogreg** [comment]
Thanks! I will try to get to this tonight EST

**Comment by imalsogreg** [comment]
@jekor Looking at newer servant-client code, I don't see special handling of `()` anymore - I believe this has been replaced by `NoContent`, and handlers over  `NoContent`-returning endpoints permit zero content types. Does using `NoContent` work for you? If not, do you mind trying out kjd `issue-51` branch? If it works we can think about merging it to `master` here, and discuss  if `servant-client` should special-case `()` too as I think it used to.

https://github.com/haskell-servant/servant/blob/master/servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs#L185-L241

**Comment by jekor** [comment]
Thanks. I've confirmed that the `issue-51` branch compiles for me, but then I found out that `'[] ()` will no longer compile with servant-server. I hadn't realized this, as the client gets compiled before the server in my build system.

NoContent works for me. Sorry for the distraction!
